// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3NC9zgAesQNKsA8G_4PbZlpAvMuhA1yM',
    appId: '1:685258165987:web:841150fee428220e0e3fd6',
    messagingSenderId: '685258165987',
    projectId: 'to-do-205ba',
    authDomain: 'to-do-205ba.firebaseapp.com',
    storageBucket: 'to-do-205ba.firebasestorage.app',
    measurementId: 'G-9JTJLT0VN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9uGbc5YBR_v5KXIIU8ThQ7Ruy1ik_5Dc',
    appId: '1:685258165987:android:15143f89bc1cac3f0e3fd6',
    messagingSenderId: '685258165987',
    projectId: 'to-do-205ba',
    storageBucket: 'to-do-205ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcLUZsj_2xM-dW0z5vnWlV_OBnakMuU7k',
    appId: '1:685258165987:ios:13eccc33764510ed0e3fd6',
    messagingSenderId: '685258165987',
    projectId: 'to-do-205ba',
    storageBucket: 'to-do-205ba.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcLUZsj_2xM-dW0z5vnWlV_OBnakMuU7k',
    appId: '1:685258165987:ios:13eccc33764510ed0e3fd6',
    messagingSenderId: '685258165987',
    projectId: 'to-do-205ba',
    storageBucket: 'to-do-205ba.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3NC9zgAesQNKsA8G_4PbZlpAvMuhA1yM',
    appId: '1:685258165987:web:530e5cb5f9e6a1e00e3fd6',
    messagingSenderId: '685258165987',
    projectId: 'to-do-205ba',
    authDomain: 'to-do-205ba.firebaseapp.com',
    storageBucket: 'to-do-205ba.firebasestorage.app',
    measurementId: 'G-J2ZBNV1WQ1',
  );
}
